---
abstract: 'Alternative Text::MicroTemplate View for Catalyst'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst: '5.90060'
  Moo: '2.000001'
  Path::Class: '0.35'
  Test::Most: '0.34'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-View-Text-MicroTemplate-PerRequest
requires:
  Catalyst::Component::ApplicationAttribute: '0'
  Catalyst::Component::InstancePerContext: '0.001001'
  CatalystX::InjectComponent: '0.025'
  Data::Perl: '0.002009'
  HTTP::Status: '0'
  Moo: '2.000001'
  Text::MicroTemplate::Extended: '0.17'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-View-Text-MicroTemplate-PerRequest/issues
  homepage: https://github.com/jjn1056/Catalyst-View-Text-MicroTemplate-PerRequest
  repository: https://github.com/jjn1056/Catalyst-View-Text-MicroTemplate-PerRequest
version: '0.001'
